query CurrentPlayersTracking($idPlayer: Int) {
    currentPlayersTracking(idPlayer: $idPlayer) {
      	IdTracking
      	IdTable
      	Description
        IdPlayer
      	Name
      	IdOperations
      	IdOperationType
      	OperationName
      	Date
      	IdPayment
      	PayDescription
      	PayInstrument
      	Denomination
      	Qty
      	Amount
    }
}