query GetMoneyBreakdown($amount: Float!, $idOperation: Int!) {
  getMoneyBreakdown(amount: $amount, idOperation: $idOperation) {
    IdPayInstr
    IdPayment
    Denomination
    Rate
    Quantity
  }
}