query GetOperationsToday($idState: Int!) {
    getOperationsToday(idState: $idState) {
        IdOperation
        IdTable
        Table
        IdPlayer
        Player
        IdUser
        UserName
        Date
        IdOperationType
        Finished
        Cancelled
        AmountIn
        AmountOut
    }
}