mutation UpdateOperation($operationInput: OperationInput!) {
  updateOperation(operationInput: $operationInput) {
    IdOperation
    Consecutive
    IdOperationType
    IdTable
    IdPlayer
    IdUser
    Date
    Finished
    Cancelled
  }
}