query GetTable($id: Int!) {
    getTable(id: $id) {
        IdTable
        Description
        IdGame
        Enabled
        InitValues {
            IdInitValue
            IdPayment
            Qty
        }    
    }
}