query GetPayments {
    getPayments {
        IdPayment
        Denomination
        IdPayInstr
        IdCurrency
        PayInstrument
      	Currency
      	Rate
      	PaymentName
        Enabled
    }
}