query GetPayments {
    getPayments {
        IdPayment
        Description
        Denomination
        IdPayInstr
        IdCoin
        PayInstrument
      	Coin
      	Rate
      	PaymentName
        Enabled
    }
}