mutation CreatePayment($paymentInput: PaymentInput!) {
    createPayment(paymentInput: $paymentInput) {
        IdPayment
        Description
        Denomination
        IdPayInstr
        IdCoin
        Enabled
    }
}