mutation CreatePayment($paymentInput: PaymentInput!) {
    createPayment(paymentInput: $paymentInput) {
        IdPayment
        Denomination
        IdPayInstr
        IdCurrency
        Enabled
        Picture
    }
}