mutation UpdatePayment($paymentInput: PaymentInput!) {
    updatePayment(paymentInput: $paymentInput) {
        IdPayment
        Description
        Denomination
        IdPayInstr
        IdCoin
        Enabled
    }
}