mutation UpdatePayment($paymentInput: PaymentInput!) {
    updatePayment(paymentInput: $paymentInput) {
        IdPayment
        Denomination
        IdPayInstr
        IdCurrency
        Enabled
        Picture
    }
}