mutation SaveCasinoInfo($casinoInfoInput: CasinoInfoInput!) {
    saveCasinoInfo(casinoInfoInput: $casinoInfoInput) {
        Id
        Name
        Address
        Phone
        IdCountry
        IdCity
    }
}