query GetPlayers {
    getPlayers {
        IdPlayer
        Name
        LastName
        StartDate
        Personal_Id
        Note
        CellPhone
        DateOfBirth
        IdCountry
        Enabled
        Deleted
        StatusInfo {
            IdOperation
            OperationName
        }
    }
}