query GetPlayers {
    getPlayers {
        IdPlayer
        Name
        LastName
        StartDate
        Personal_Id
        Passport_Number
        Note
        CellPhone
        DateOfBirth
        IdCountry
        Enabled
        Deleted
    }
}