query GetPlayers {
    getPlayers {
        IdPlayer
        Name
        LastName
        StartDate
        Personal_Id
        Note
        CellPhone
        DateOfBirth
        IdCountry
        Country {
            IdCountry
            Name
        }
        Enabled
        Deleted
        StatusInfo {
            IdOperation
            OperationName
        }
        IdCategory
        Category {
            IdCategory
            Description
        }
    }
}