mutation CreatePlayer($playerInput: PlayerInput!) {
    createPlayer(playerInput: $playerInput) {
        IdPlayer
        Name
        LastName
        StartDate
        Personal_Id
        Note
        CellPhone
        Enabled
        IdCountry
    }
}