query GetPlayer($id: Int!) {
    getPlayer(id: $id) {
        IdPlayer
        Name
        LastName
        StartDate
        Personal_Id
        Note
        CellPhone
        DateOfBirth
        IdCountry
        Enabled
    }
}