query GetPlayer($id: Int!) {
    getPlayer(id: $id) {
        IdPlayer
        Name
        LastName
        StartDate
        Personal_Id
        Passport_Number
        Note
        CellPhone
        Enabled
        IdCountry
    }
}