mutation UpdatePlayer($playerInput: PlayerInput!) {
    updatePlayer(playerInput: $playerInput) {
        IdPlayer
        Name
        LastName
        Personal_Id
        Note
        CellPhone
        Enabled
        IdCountry
    }
}